package com.github.yumelira.yumebox.service

import android.content.Context
import com.github.yumelira.yumebox.service.runtime.records.ImportedDao
import com.github.yumelira.yumebox.service.runtime.records.PendingDao
import com.github.yumelira.yumebox.service.runtime.records.ProfileStore
import com.github.yumelira.yumebox.service.runtime.entity.Imported
import com.github.yumelira.yumebox.service.runtime.entity.Pending
import com.github.yumelira.yumebox.service.runtime.entity.Profile
import com.github.yumelira.yumebox.service.remote.IFetchObserver
import com.github.yumelira.yumebox.service.remote.IProfileManager
import com.github.yumelira.yumebox.service.runtime.config.ServiceStore
import com.github.yumelira.yumebox.service.runtime.util.directoryLastModified
import com.github.yumelira.yumebox.service.runtime.util.generateProfileUUID
import com.github.yumelira.yumebox.service.runtime.util.importedDir
import com.github.yumelira.yumebox.service.runtime.util.pendingDir
import com.github.yumelira.yumebox.service.runtime.util.sendProfileChanged
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.io.FileNotFoundException
import java.net.URLDecoder
import java.nio.charset.StandardCharsets
import java.util.*
import com.github.yumelira.yumebox.service.StatusProvider

class ProfileManager(private val context: Context) : IProfileManager,
    CoroutineScope by CoroutineScope(Dispatchers.IO) {
    private val store = ServiceStore()

    private fun isAutoGeneratedProfileName(name: String): Boolean {
        val normalized = name.trim()
        if (normalized.isBlank()) return true
        if (normalized.startsWith("temp_", ignoreCase = true)) return true

        val lowered = normalized.lowercase(Locale.getDefault())
            .replace(" ", "")
            .replace("_", "")
            .replace("-", "")

        return lowered in setOf(
            "newprofile",
            "remotefile",
            "新配置",
            "新配置文件"
        )
    }

    private fun deriveNameFromSource(source: String): String? {
        return runCatching {
            source.substringBefore('?')
                .substringBefore('#')
                .substringAfterLast('/')
                .substringBeforeLast('.')
                .let { URLDecoder.decode(it, StandardCharsets.UTF_8.name()) }
                .trim()
                .takeIf { it.isNotBlank() }
        }.getOrNull()
    }

    private fun resolveDisplayName(name: String, source: String): String {
        if (!isAutoGeneratedProfileName(name)) return name
        return deriveNameFromSource(source) ?: name
    }
    
    init {
        launch {
            context.pendingDir.mkdirs()
            context.importedDir.mkdirs()
        }
    }

    override suspend fun create(type: Profile.Type, name: String, source: String): UUID {
        val uuid = generateProfileUUID()
        val normalizedName = name.trim().ifBlank { "New Profile" }
        val pending = Pending(
            uuid = uuid,
            name = normalizedName,
            type = type,
            source = source,
            interval = 0,
            upload = 0,
            total = 0,
            download = 0,
            expire = 0,
        )

        PendingDao.insert(pending)

        context.pendingDir.resolve(uuid.toString()).apply {
            deleteRecursively()
            mkdirs()

            @Suppress("BlockingMethodInNonBlockingContext")
            resolve("config.yaml").createNewFile()
            resolve("providers").mkdir()
        }

        return uuid
    }

    override suspend fun clone(uuid: UUID): UUID {
        val newUUID = generateProfileUUID()

        val imported = ImportedDao.queryByUUID(uuid)
            ?: throw FileNotFoundException("profile $uuid not found")

        val pending = Pending(
            uuid = newUUID,
            name = imported.name,
            type = Profile.Type.File,
            source = imported.source,
            interval = imported.interval,
            upload = imported.upload,
            total = imported.total,
            download = imported.download,
            expire = imported.expire,
        )

        cloneImportedFiles(uuid, newUUID)

        PendingDao.insert(pending)

        return newUUID
    }

    override suspend fun patch(uuid: UUID, name: String, source: String, interval: Long) {
        val pending = PendingDao.queryByUUID(uuid)

        if (pending == null) {
            val imported = ImportedDao.queryByUUID(uuid)
                ?: throw FileNotFoundException("profile $uuid not found")

            cloneImportedFiles(uuid)

            PendingDao.insert(
                Pending(
                    uuid = imported.uuid,
                    name = name,
                    type = imported.type,
                    source = source,
                    interval = interval,
                    upload = 0,
                    total = 0,
                    download = 0,
                    expire = 0,
                )
            )
        } else {
            val newPending = pending.copy(
                name = name,
                source = source,
                interval = interval,
                upload = 0,
                total = 0,
                download = 0,
                expire = 0,
            )

            PendingDao.update(newPending)
        }
    }

    override suspend fun update(uuid: UUID, callback: IFetchObserver?) {
        ProfileProcessor.update(context, uuid, callback)
    }

    override suspend fun commit(uuid: UUID, callback: IFetchObserver?) {
        ProfileProcessor.apply(context, uuid, callback)
    }

    override suspend fun release(uuid: UUID) {
        ProfileProcessor.release(context, uuid)
    }

    override suspend fun delete(uuid: UUID) {
        ProfileProcessor.delete(context, uuid)
    }

    override suspend fun queryByUUID(uuid: UUID): Profile? {
        return resolveProfile(uuid)
    }

    override suspend fun queryAll(): List<Profile> {
        val uuids = withContext(Dispatchers.IO) {
            (ImportedDao.queryAllUUIDs() + PendingDao.queryAllUUIDs()).distinct()
        }

        val orderIndex = ProfileStore.loadProfileOrder()
            .withIndex()
            .associate { it.value to it.index }

        return uuids.mapNotNull { resolveProfile(it) }
            .sortedWith(compareBy<Profile> { orderIndex[it.uuid] ?: Int.MAX_VALUE }
                .thenByDescending { it.updatedAt })
    }

    override suspend fun queryActive(): Profile? {
        val active = store.activeProfile ?: return null

        // 如果 active 指向一个不存在的 profile（例如被删除），清掉避免 UI 抖动/落后
        return if (ImportedDao.exists(active) || PendingDao.exists(active)) {
            resolveProfile(active)
        } else {
            store.activeProfile = null
            null
        }
    }

    override suspend fun setActive(profile: Profile) {
        ProfileProcessor.active(context, profile.uuid)
    }

    override suspend fun clearActive(profile: Profile) {
        store.activeProfile = null
        StatusProvider.currentProfile = null
        context.sendProfileChanged(profile.uuid)
    }

    override suspend fun reorder(uuids: List<UUID>) {
        val existing = (ImportedDao.queryAllUUIDs() + PendingDao.queryAllUUIDs()).distinct()
        val existingSet = existing.toSet()

        val normalized = buildList {
            uuids.forEach { uuid ->
                if (uuid in existingSet && uuid !in this) add(uuid)
            }
            existing.forEach { uuid ->
                if (uuid !in this) add(uuid)
            }
        }

        ProfileStore.saveProfileOrder(normalized)
    }

    private suspend fun resolveProfile(uuid: UUID): Profile? {
        val imported = ImportedDao.queryByUUID(uuid)
        val pending = PendingDao.queryByUUID(uuid)

        val active = store.activeProfile
        val rawName = pending?.name ?: imported?.name ?: return null
        val type = pending?.type ?: imported?.type ?: return null
        val source = pending?.source ?: imported?.source ?: return null
        val name = resolveDisplayName(rawName, source)
        val interval = pending?.interval ?: imported?.interval ?: return null
        val upload = pending?.upload ?: imported?.upload ?: return null
        val download = pending?.download ?: imported?.download ?: return null
        val total = pending?.total ?: imported?.total ?: return null
        val expire = pending?.expire ?: imported?.expire ?: return null

        return Profile(
            uuid,
            name,
            type,
            source,
            active != null && (imported?.uuid == active || pending?.uuid == active),
            interval,
            upload,
            download,
            total,
            expire,
            resolveUpdatedAt(uuid),
            imported != null,
            pending != null
        )
    }

    private fun resolveUpdatedAt(uuid: UUID): Long {
        return context.pendingDir.resolve(uuid.toString()).directoryLastModified
            ?: context.importedDir.resolve(uuid.toString()).directoryLastModified
            ?: -1
    }

    private fun cloneImportedFiles(source: UUID, target: UUID = source) {
        val s = context.importedDir.resolve(source.toString())
        val t = context.pendingDir.resolve(target.toString())

        if (!s.exists())
            throw FileNotFoundException("profile $source not found")

        t.deleteRecursively()

        s.copyRecursively(t)
    }

}
